name: "ruff-action"
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Ruff Format check
        uses: astral-sh/ruff-action@v3
        with:
          args: "format --check --exclude '*.ipynb'"
      - name: Ruff Lint Check
        run: ruff check
      
